on:
  push: {}

name: Checkout, install, lint and deploy

jobs:
  checkout-and-install:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --check-files
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: checkout-and-install
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - run: yarn lint

  build-and-deploy-review:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref != 'refs/heads/master'
    steps:
      - run: |
          yarn global add vercel@23.1.2
          vercel -t ${{ secrets.VERCEL_TOKEN }} --name funnyface --confirm

  build-and-deploy-production:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/master'
    steps:
      - run: |
          yarn global add vercel@23.1.2
          vercel -t ${{ secrets.VERCEL_TOKEN }} --name funnyface --confirm --prod
